defaults: &defaults
    docker:
        - image: circleci/openjdk:8-jdk
    working_directory: /home/circleci/project

version: 2.1
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
            - restore_cache:
                keys:
                    - scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
            - run:
                command: ./sbin/buildAll.sh               
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - CitibikeApiProducer/build/
                    - RawDataSaver/target/
                    - StationConsumer/target/
                    - StationTransformerNYC/target/
            - run:
                command: ls /home/circleci/project/
            - save_cache:
                key: scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
                paths:
                    - "~/.ivy2/cache"
            - save_cache:
                key: java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
                paths:
                    - "~/.gradle"

    upload:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                  - "23:1f:be:07:c1:29:10:65:fb:d8:7a:a2:35:1d:01:6d"
            - run:
                command: ./sbin/upload.sh $BASTION_PUBLIC_IP $TRAINING_COHORT $CIRCLE_SHA1

    upgrade:
        <<: *defaults
        parameters:
            namespace:
                type: string
        steps:
            - checkout
            - attach_workspace:
                  at: /home/circleci/project
            - add_ssh_keys:
                  fingerprints:
                      - "23:1f:be:07:c1:29:10:65:fb:d8:7a:a2:35:1d:01:6d"
            - run:
                  command: ./sbin/upgrade.sh $BASTION_PUBLIC_IP $TRAINING_COHORT $CIRCLE_SHA1 << parameters.namespace >>

    deploy:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                  - "23:1f:be:07:c1:29:10:65:fb:d8:7a:a2:35:1d:01:6d"
            - run:
                command: ./sbin/deploy.sh $BASTION_PUBLIC_IP $TRAINING_COHORT

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: 
                            - master
                            - start
            - upload:
                requires:
                    - build
            - upgrade:
                namespace: test
                requires:
                    - upload
            - approve-deploy:
                type: approval
                requires: 
                    - upload
            - deploy:
                requires:
                    - approve-deploy
